web:
    restart: always
    build: ./web
    links:
        - db
        - rabbitmq
    environment:
        - LODSTATS_DB=db
        - RABBITMQ=rabbitmq
        - VIRTUAL_HOST=lodstats.aksw.org

rabbitmq:
    restart: always
    image: rabbitmq:3.6.1

db:
    restart: always
    build: ./db
