version: '3'

services:
  web:
      build: ./web
      links:
          - db
          - rabbitmq
      environment:
          - LODSTATS_DB=db
          - RABBITMQ=rabbitmq
      expose:
          - 80
  rabbitmq:
      image: rabbitmq:3.6.1

  db:
      build: ./db

  virtuoso:
      build: ./virtuoso
      environment:
          - DBA_PASSWORD=mypass
          - SPARQL_UPDATE=false
          - DEFAULT_GRAPH=http://lodstats.aksw.org/
      ports:
          - "8890:8890"

  nginx:
      build: ./nginx
      links:
          - web
          - virtuoso
      environment:
          - VIRTUAL_HOST=lodstats.aksw.org,stats.lod2.eu
      ports:
          - "80:80"
