web:
    restart: always
    build: ./web
    links:
        - db
        - rabbitmq
    environment:
        - LODSTATS_DB=db
        - RABBITMQ=rabbitmq

rabbitmq:
    restart: always
    image: rabbitmq:3.6.1

db:
    restart: always
    build: ./db

virtuoso:
    restart: always
    build: ./virtuoso
    environment:
        - DBA_PASSWORD=dba
        - SPARQL_UPDATE=false
        - DEFAULT_GRAPH=http://lodstats.aksw.org/

nginx:
    build: ./nginx
    restart: always
    links:
        - web
        - virtuoso
    environment:
        - VIRTUAL_HOST=lodstats.aksw.org
