version: '3'

services:
  web:
      build: ./web
      links:
          - db
          - rabbitmq
      environment:
          - LODSTATS_DB=db
          - RABBITMQ=rabbitmq
      expose:
          - 8080
      volumes:
          # Set your own path for local development
          - /home/k00ni/Documents/LODStats_WWW/rdfstats:/lodstats_www/rdfstats
  rabbitmq:
      image: rabbitmq:3.6.1

  db:
      build: ./db
      environment:
        - POSTGRES_USER=postgres

  virtuoso:
      build: ./virtuoso
      environment:
          - DBA_PASSWORD=mypass
          - SPARQL_UPDATE=false
          - DEFAULT_GRAPH=http://lodstats.aksw.org/
          - LOAD_DUMP=false # true or false to determine when to load dump file
      ports:
          - "8890:8890"

  nginx:
      build: ./nginx
      links:
          - web
          - virtuoso
      environment:
          - VIRTUAL_HOST=lodstats.aksw.org,stats.lod2.eu
      ports:
          - "8080:80"
