version: '3'

services:
  lodstats-web:
    image: dicegroup/lodstats-web:1.0.0
    environment:
      - LODSTATS_DB=db
      - RABBITMQ=rabbitmq
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
      image: postgres:9.6.5
      volumes:
        - ./db/scripts:/docker-entrypoint-initdb.d
        - ./db:/data
      deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure

  rabbitmq:
      image: rabbitmq:3.6.1
      deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure

  virtuoso:
      image: tenforce/virtuoso:1.3.0-virtuoso7.2.4
      environment:
          - DBA_PASSWORD=maipass
          - SPARQL_UPDATE=false
          - DEFAULT_GRAPH=http://lodstats.aksw.org/
      deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure

  nginx-proxy:
    image: nginx:1.13.6
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - 80:80
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
